group: travis_latest
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: ZTHAAJX7kCAUQ3kFFuR3WSSbufTM7cU6x1+noHuJcxaTDJK8xrLHs8nu87nImJycSpQpGM0NdGXDGHMi9dqroctEGyucSqrFFpsEPhHGttPr1rmuY8WUikReGbi8/MX5fw1arX8VNXBguZi90p4YT21f3zRhYPWXkathL+oCj+0mG/lQF92txWLm8mUwUOrsVt/Qiw7KTPX1mF7fmBBSjomLPNn9nlNHA6oZO0RULz7j6EnkwwkF37sGtWeoLvZpgKrdQ9fyJE8radlyFkYHbF21v1cy4kDNVLDwt1b2DymAfUFSfzHu5lnEbYnhTJJwu561v7Y4OGhkyEeyl1U8n3AgcQXzFPciRecuOS4vy2+C9EfQizaRVR2WymCvKjG2clMyMP7N57notuvqAhgnIiUFayU74DT2K39VzOi/ezKzF4FQwSCbVkOhHRX7iA7iEFskG0siDBmsuFz3FFhmFpljIrMxbtOkVdeEzLZUZmWuJigAtQo9EaF0nwfUQR1dIspRVGQVHoxxNxgcdR8KeljMBPjX42uz/x7LADXl5VzwnHxTahT247ICp3KIFsfaa04Rx/x4tfUYr7xj2hSNvJartNsIPfO9sc87hqlc7iMW0ogueZbgHQ1daS9s0LlFcFhfyCb78gR1T89OhG6Dd77tRdd3NW300ptds7sVhdY=
  - secure: VJ5HZdaa21FfjCykMTcxCfgLu6XSMhcQtXtw7rMuK4Uf/GhvWYSlZOFgGkaJgwZgWQQsV2I6ULCihLhOJZen3Oye0R8oJmC3+G8AX9zLl360lsJzYHOhK6BKblz31HNPEL6PYLQMltH72I2BTnJh84hja9sNO5OuTPvuIC07h0YiZSXvMWI7IaQUPV74HrGQf/o4rpFsfSoIBLM7cAlqsu66wbyhCto3DdFvt+M3pCZLsG2YF2EqJfKLi0m08rrb7ZXYivry1HNwEVDxlqpcxaGYKrd/er3Mb9llx8F/yoxXMopHhNjSLyBNoRwaA0r/T+3q6ymRaAC89uQmXoRWJqwDV7qoXm6lUlixGs8tfiwnzIyMsKeMuOoJiMcKsk5IpJILv6sITFE2foR0idVPXZ2jOyqwK97PKvKcoxqQAnUWFb8dn7EtLymtpng/keANRw5XoSakTKWh2E8v5SSV0mmkzs7SqalQUnYLBPQZLHf7ALpf4zbZN6N7FcWTMRj3S2cX6R8jwLB5Mqe4/wka9bvCb4DbM4wBRdWo62PzuGxijTupGaO90x1cTJJZuOxxtiLYzyGI0imT61XliQ82XewopC0VuL37tu7YYS5cInEeT14//oWagiAwavSvXGwMAwIY9Gxf2f+hf6+1nUgjhqa4sCr9iEYGEnvV02fVGDM=
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
