group: travis_latest
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: xc/UFBAnzPPTSiZLvxvNDI8Y7rUjoPHwOCr9xBDxlL2XWQXlVKsJxyfKB9hCvGgXf9Cjnr30q7+8nVv29Kmw31eIlOjpi3iimvFeThhCNwKd2vywgcebRZgNsDUkpUcSC2DILclecybk8GP88VLwEf8KQ5g8UiLX85ICrlGTn5RUqNp5I+dtcL3RnvlXKeGMUfOIkPgrfeUBOZHQ4jnNArjEmWtXZPnhKIV338Byr5ukJPFTjAifS4bJvj+kG2PEv8c7Ia70TQ7bIUYXQ7seYBkW7UrXNq5SPGwxJM617D35NLkHS03792iEysxSjH4hEVKwvL3aV78ksfvufsFAQxtx3fNev5Zz3mR/rgfC9b+bqGrhqEOqig/fCE9ZHuJ+5KyzKx1VaLHYMoTscgW+QlbrD902Dj+fkPD0HaCodHXtWZvGOkWGlbgMeE2b6AREagiYPeOebdQZgkgV1yVObkyJaMXrX02BOYL91rZlQomkg+yJ0fibFhasdo4chn+kdISErBxxOWzxfIo8/0oL5VqN6XGUd1+m/zVQ7sqQ/XkEngySiXJyiNxQNuxmCm2LYSdea7IgUmgWLOTmhSt7yncFJ94yc/ePUpKIgYQ8a7W+3pjZjYAJG8FdmD9gWrzNvxKHPaU/BtwdR8zN9V0xzbZ3fdosDsLBiJNMi5WwBEU=
  - secure: cqb0fVUs2xgdsik8UGijuY7bgX/gyx4EP86hZy2uEHiYr9W9RPThUHfDdxG9flacZAM6bXEW26hBylSX63W7Um83RJW1+Zy3rmuRHUrIwoi1IEMNK45qxhcby+faBJ0FFfLZW7bKq0MxebsSaIaW74mfrG9J/tsdTIXR9+8XoIZjuVrex52U8TORT6lUrsJ+hW17dZ/U1IRXLrnMjma1Aejkk/fjZ+F506rWHmOO8A9/UbqMrEiDzvp8sh//qVNSI6CzigxOQDHLTIqfDljoHCN7KBIyVug2bwZx02NtkXkSN/7pEnDaEKyBzpj/FJmdB+tqwe2BjTbNbUGC1aY3mLr9Zos6RyuWdC46WztyGn9ia0igd4kfy3yrLZN7tLYD92QQgGjSTokIneMnlj8o/HCItRmLBUrO/2q2vvC3FV1gYWClfVPBfdCNJ03DCvsQY9YU1ydolvewWw+k93yMNeCvmI1TdGwW9+HRf/V2lQ1fLj5gVY2IY1MdLyJ2dOHZHiNrRFxd6icjZrljaYkk3ZzmuXmZ5wlhm/iCKrKaYwvl/49VQ7nWfYl2+RH/BrXQ4xYA+/YlmMG5SI0lDQVo4mmriIgNZe9kMc5pu5nPhGM2/CtSrk2saZ1sjTwOLUYX/ps4WKStHGaQTN6psk60nP0GcQ/w3fTPCyAUYjg/GQI=
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
